### ISSUE TITLE
one question about the goal of inferring

### ISSUE THREAD

**Issue by 1223haohao** [intuitive-robots/beso#2]
Thank you for your excellent work. 
I have a question about the 'goal'. During the training process, we have offline training data, so we can easily obtain the goal. However, during the inference process, how do we obtain the goal for the inference task? Does the simulation environment itself provide the goal, or are there other ways to generate the goal?

**Comment by mbreuss** [comment]
Hi,

thanks for the interest in our work! During inference we take example final states from rollouts of the training data and give it to the model as a desired goal state.
This idea has been adopted from https://github.com/jeffacce/play-to-policy that came up with that goal-conditioned variant of these two benchmarks. 
Hope that helps!
