### ISSUE TITLE
Training and Evaluation of CALVIN Dataset

### ISSUE THREAD

**Issue by qifang804** [intuitive-robots/beso#4]
Hi authors, thank you for providing the code base of beso, it's a amazing work! I am interested in working with the model on CALVIN dataset, wondering that if current code will extend to handle that dataset?

It would be great of help if we can have the training, evaluation and pretrained weight. Many thanks!

**Comment by mbreuss** [comment]
HI, our follow-up work called MDT was recently published with pretrained weights on CALVIN ABCD and D. 

https://github.com/intuitive-robots/mdt_policy

Its an extension of BESO that fixes some of its drawbacks and learns from goal images and language goals together. I will also upload code to run a slight variation of BESO with Action Chunking for CALVIN soon that trains on langauge only CALVIN data but the results are worse than the MDT ones. Hope that helps :)
